ci: Make sure the proper CHANGELOG.md file is read for addon

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -64,11 +64,11 @@ jobs:
           fi
 
       - name: Check changelog for new version
-        if: hashFiles('CHANGELOG.md')
+        if: hashFiles('.${{ inputs.addon }}/CHANGELOG.md')
         run: |
           VERSION="${{ steps.next_version.outputs.next_version }}"
-          if ! grep -q "## \[v$VERSION\]" CHANGELOG.md; then
-            echo "Error: Changelog section for version v$VERSION not found in CHANGELOG.md"
+          if ! grep -q "## \[v$VERSION\]" ./${{ inputs.addon }}/CHANGELOG.md; then
+            echo "Error: Changelog section for version v$VERSION not found in ./${{ inputs.addon }}/CHANGELOG.md"
             echo "Please add a changelog entry for version v$VERSION"
             exit 1
           fi
